### PR TITLE
Couple of improvements

### PR DESCRIPTION
**Pull request by rzane**
Here's a summary of the changes I made:
- When I first tried to use circle-cli, it was failing because my repo url didn't end in `.git`, so the regex test was failing. It's probably a good idea to use a well tested library to handle the parsing of git uris, since they can come in many shapes and forms.
- There's no need to add to the load path in the executable. Running `bin/circle` will fail to resolve to `lib`, so you need to run with `bundle exec` while developing. Once the gem is installed, everything works properly.
- Added thor to handle the command invocation, help info, and a million other things.
- The `open` command only works on OSX. Linux and windows are a little bit different, and the `launchy` gem provides a tried and true technique for doing this sort of thing.
- Also, this gem wasn't really using the circle CI api. I removed all of the github integration (sorry), and make it rely entirely on 1 api.
- I added a login command to open the create token page and add your token.
- Added commands to trigger/cancel builds
- Added a command to list the status of all recent builds on all branches
- The status command now shows build steps and failing specs

### CODE REVIEW

**Comment by rzane** [comment]
hey @codeurge, what do you think?

**Comment by codeurge** [comment]
Hey @rzane, first and foremost, thank you very much for you contribution here. This PR really goes above and beyond some of the ideas I had in mind but haven't had a chance to work on yet.

That said, I'd really like a chance to look a bit deeper into the changes made here, and see if I have any suggestions or concerns. But overall, I think this looks really solid. Unfortunately, the next couple of days are pretty hectic with interviews (know anyone hiring for a full stack dev?) and I may not get a chance to look more until Friday.

Thanks again - I've already pulled down locally and built the gem. This really looks great and I'm looking forward to reading through it more.

**Comment by rzane** [comment]
Sounds good. I'm in no rush!

Good luck with the interviews!

**Comment by codeurge** [comment]
Sorry again for the delay @rzane - going to finish looking at this tonight, I promise! :100:

**Comment by codeurge** [comment]
Overall I think this is a solid improvement, and gives a really good foundation to build upon for future releases. Thanks a bunch for the contribution! :+1:

**Comment by rzane** [comment]
Great thanks! Is a push to rubygems in order?

**Comment by codeurge** [comment]
Yeah, absolutely - before EOD I'm going to update the Readme a bit to reflect the changes and push out a new version.

**Comment by codeurge** [comment]
@rzane New version pushed to rubygems; I've bumped to 0.1.0 as this is a huge functionality improvement over 0.0.2 and will be the base of any improvements moving forward.

Readme updated to reflect new functionality, and added a gem to show just how awesome it is.

Thanks again and again!

**Comment by rzane** [comment]
Woot woot!

**Pull request merged**
